// Itinerary configuration data.
// Edit this file when trip details change.
window.ITINERARY_DATA = {
  trip: {
    title: "Japan 2026",
    subtitle: "June 11 - July 2, 2026",
    summary:
      "Fort Lauderdale -> Montreal -> Tokyo -> Shibuya stay -> Celebrity Millennium cruise -> Tokyo -> Montreal -> Fort Lauderdale",
    startDate: "2026-06-11",
    endDate: "2026-07-02",
    returnDate: "2026-07-02",
  },
  stats: [
    {
      label: "Total trip dates",
      value: "June 11 - July 2, 2026",
      detail: "22 days including flights, Tokyo stay, and cruise journey.",
    },
    {
      label: "Tokyo stay",
      value: "June 13 - June 19",
      detail: "Airbnb in Shibuya before embarking on the cruise.",
    },
    {
      label: "Cruise dates",
      value: "June 19 - July 1",
      detail: "Celebrity Millennium, 12-night sailing with final overnight included.",
    },
    {
      label: "Return date",
      value: "July 2, 2026",
      detail: "Montreal connection completes the route back to Fort Lauderdale.",
    },
  ],
  timeline: [
    {
      id: "outbound",
      type: "flight",
      title: "Outbound flights",
      dateLabel: "June 11 - June 13",
      route: "FLL -> YUL -> NRT",
      summary: "Evening departure from Fort Lauderdale, overnight connection, then nonstop to Tokyo.",
      details: [
        { label: "June 11", value: "Air Canada AC 1611, FLL -> YUL, departure 8:55 PM ET" },
        { label: "June 12", value: "Air Canada AC 5, YUL -> NRT, departure 1:05 PM ET" },
        { label: "Arrival", value: "June 13 arrival in Japan, followed by transfer to Airbnb in Shibuya" },
        { label: "Travel note", value: "Keep transfer details and arrival documents easy to reach." },
      ],
    },
    {
      id: "shibuya",
      type: "lodging",
      title: "Shibuya stay",
      dateLabel: "June 13 - June 19",
      route: "Tokyo base",
      summary: "A Tokyo base in Shibuya for settling in, exploring, and preparing for embarkation.",
      details: [
        { label: "Stay", value: "Airbnb in Shibuya" },
        { label: "Window", value: "June 13 through June 19, 2026" },
        { label: "Arrival day", value: "June 13 transfer from Narita to Shibuya" },
        { label: "Planning note", value: "Good window for neighborhood dining, shopping, and reservations." },
      ],
    },
    {
      id: "cruise",
      type: "cruise",
      title: "Celebrity Millennium cruise",
      dateLabel: "June 19 - July 1",
      route: "Tokyo -> Japan & Korea -> Tokyo",
      summary: "A 12-night cruise through Japan and Busan, with the final overnight already included.",
      details: [
        { label: "Ship", value: "Celebrity Millennium" },
        { label: "Embarkation", value: "June 19 in Tokyo" },
        { label: "Disembarkation", value: "July 1 with same-day airport transfer planning" },
        { label: "Cruise note", value: "Center timing and packing around the July 1 evening Narita flight." },
      ],
    },
    {
      id: "return",
      type: "flight",
      title: "Return flights",
      dateLabel: "July 1 - July 2",
      route: "NRT -> YUL -> FLL",
      summary: "Disembark in Tokyo, head to Narita, then return home through Montreal.",
      details: [
        { label: "July 1", value: "Air Canada AC 6, NRT -> YUL, departure 5:35 PM JST" },
        { label: "July 2", value: "Air Canada AC 1602, YUL -> FLL, departure 8:10 AM ET" },
        { label: "Connection", value: "Montreal transit before the final leg to Fort Lauderdale" },
        { label: "Departure note", value: "Build in comfortable transfer margin from the port to Narita." },
      ],
    },
  ],
  segments: [
    {
      type: "flight",
      title: "Outbound flights",
      kicker: "Transit",
      dateLabel: "June 11 - June 13",
      route: "FLL -> YUL -> NRT",
      description: "A two-leg outbound route with an overnight connection in Montreal before arrival in Japan.",
      meta: ["Air Canada AC 1611", "Air Canada AC 5"],
      details: [
        { label: "Leg 1", value: "June 11, FLL -> YUL, departure 8:55 PM ET" },
        { label: "Leg 2", value: "June 12, YUL -> NRT, departure 1:05 PM ET" },
        { label: "Arrival", value: "June 13 arrival and transfer to Shibuya" },
      ],
    },
    {
      type: "lodging",
      title: "Shibuya stay",
      kicker: "Lodging",
      dateLabel: "June 13 - June 19",
      route: "Tokyo, Japan",
      description: "A calm Tokyo home base for recovery, city exploration, and pre-cruise planning.",
      meta: ["Airbnb", "6 nights"],
      details: [
        { label: "Property", value: "Airbnb in Shibuya" },
        { label: "Check-in window", value: "After arriving in Japan on June 13" },
        { label: "Focus", value: "Tokyo exploration, dining plans, and cruise embarkation prep" },
      ],
    },
    {
      type: "cruise",
      title: "Celebrity Millennium cruise",
      kicker: "Cruise",
      dateLabel: "June 19 - July 1",
      route: "Tokyo round trip",
      description: "The centerpiece of the itinerary, mixing city departures, scenic sea days, and port stops.",
      meta: ["12 nights", "Final overnight included"],
      details: [
        { label: "Embarkation", value: "Tokyo on June 19" },
        { label: "Highlights", value: "Kyoto/Osaka, Kochi, Busan, Nagasaki, Kagoshima, and Shimizu" },
        { label: "Disembarkation", value: "July 1 followed by airport transfer day" },
      ],
    },
    {
      type: "flight",
      title: "Return flights",
      kicker: "Transit",
      dateLabel: "July 1 - July 2",
      route: "NRT -> YUL -> FLL",
      description: "Post-cruise departure from Narita followed by the final overnight connection home.",
      meta: ["Air Canada AC 6", "Air Canada AC 1602"],
      details: [
        { label: "Leg 1", value: "July 1, NRT -> YUL, departure 5:35 PM JST" },
        { label: "Leg 2", value: "July 2, YUL -> FLL, departure 8:10 AM ET" },
        { label: "Priority", value: "Coordinate disembarkation, luggage, and airport timing smoothly" },
      ],
    },
  ],
  ports: [
    {
      date: "June 19",
      title: "Tokyo departure",
      location: "Tokyo, Japan",
      note: "Embark and settle in before sail-away.",
      coords: [35.6298, 139.77],
    },
    {
      date: "June 20",
      title: "At sea",
      location: "Pacific waters",
      note: "Recovery day and onboard reset.",
      coords: [34.95, 136.95],
    },
    {
      date: "June 21",
      title: "Kyoto/Osaka",
      location: "Kyoto / Osaka region",
      note: "First full Kansai sightseeing day.",
      coords: [34.6577, 135.4297],
    },
    {
      date: "June 22",
      title: "Kyoto/Osaka",
      location: "Kyoto / Osaka region",
      note: "Second port day for a deeper Kyoto or Osaka plan.",
      coords: [34.6577, 135.4297],
    },
    {
      date: "June 23",
      title: "Kochi",
      location: "Kochi, Japan",
      note: "Historic and coastal stop on Shikoku.",
      coords: [33.4938, 133.5321],
    },
    {
      date: "June 24",
      title: "At sea",
      location: "Cruising day",
      note: "Slower day for ship time, dining, and rest.",
      coords: [34.2, 130.95],
    },
    {
      date: "June 25",
      title: "Busan",
      location: "Busan, South Korea",
      note: "International port day with markets and waterfront energy.",
      coords: [35.1028, 129.0403],
    },
    {
      date: "June 26",
      title: "Nagasaki",
      location: "Nagasaki, Japan",
      note: "Historic harbor city with layered cultural sites.",
      coords: [32.7448, 129.8737],
    },
    {
      date: "June 27",
      title: "Kagoshima",
      location: "Kagoshima, Japan",
      note: "Southern Kyushu stop with volcanic scenery nearby.",
      coords: [31.5966, 130.5571],
    },
    {
      date: "June 28",
      title: "At sea",
      location: "Cruising day",
      note: "Onboard day before the Mt. Fuji area approach.",
      coords: [33.2, 135.4],
    },
    {
      date: "June 29",
      title: "Shimizu / Mt. Fuji area",
      location: "Shimizu, Japan",
      note: "Scenic gateway for Fuji views and excursions.",
      coords: [35.0158, 138.4898],
    },
    {
      date: "June 30",
      title: "Return toward Tokyo",
      location: "Approach to Tokyo",
      note: "Final full sailing day heading back to the capital.",
      coords: [35.33, 139.25],
    },
    {
      date: "July 1",
      title: "Disembark / airport transfer day",
      location: "Tokyo, Japan",
      note: "Disembark in Tokyo and transfer for the evening Narita flight.",
      coords: [35.6298, 139.77],
    },
  ],
  notes: [
    {
      title: "Packing notes",
      items: [
        "Keep passports, cruise documents, and both Air Canada confirmations together.",
        "Pack one compact arrival-day bag for the transfer to Shibuya and the first Tokyo evening.",
        "Bring lightweight layers for city walking, sea days, and cool indoor spaces.",
      ],
    },
    {
      title: "Booking reminders",
      items: [
        "Confirm Airbnb check-in instructions and backup contact timing before departure.",
        "Review cruise boarding requirements, luggage tags, and any specialty reservations.",
        "Double-check the July 1 Narita transfer plan so the 5:35 PM JST departure stays comfortable.",
      ],
    },
    {
      title: "Reservation ideas",
      items: [
        "Shortlist a few Shibuya and central Tokyo dinner spots for the pre-cruise stay.",
        "Consider advance booking for high-demand Tokyo attractions in mid-June.",
        "Sketch optional port priorities for Kyoto/Osaka, Busan, and Shimizu.",
      ],
    },
    {
      title: "Airport transfer notes",
      items: [
        "Timezone key for this plan: ET = Eastern Time, JST = Japan Standard Time.",
        "Save airport, Airbnb, and terminal addresses offline before departure.",
        "Compare Narita Express, airport bus, and private transfer comfort for the return day.",
        "Keep luggage handling simple on July 1 so port exit to airport feels smooth.",
      ],
    },
  ],
};
