// Itinerary configuration data.
// Edit this file when trip details change.
window.ITINERARY_DATA = {
  trip: {
    title: "Japan 2026",
    subtitle: "June 11 - July 2, 2026",
    summary:
      "Fort Lauderdale -> Montreal -> Tokyo -> Shibuya stay -> Celebrity Millennium cruise -> Tokyo -> Montreal -> Fort Lauderdale",
    startDate: "2026-06-11",
    endDate: "2026-07-02",
    returnDate: "2026-07-02",
  },
  stats: [
    {
      label: "Tokyo stay",
      value: "June 13 - June 19",
      detail: "Airbnb in Shibuya before embarking on the cruise.",
    },
    {
      label: "Cruise dates",
      value: "June 19 - July 1",
      detail: "Celebrity Millennium, 12-night sailing with final overnight included.",
    },
    {
      label: "Return date",
      value: "July 2, 2026",
      detail: "Montreal connection completes the route back to Fort Lauderdale.",
    },
  ],
  timeline: [
    {
      id: "outbound",
      type: "flight",
      title: "Outbound flights",
      dateLabel: "June 11 - June 13",
      route: "FLL -> YUL -> NRT",
      summary: "Evening departure from Fort Lauderdale, overnight connection, then nonstop to Tokyo.",
      details: [
        {
          label: "June 11",
          value: "Air Canada AC 1611, FLL -> YUL, departure 8:55 PM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=1611&t=20260611&o=FLL&c=AC&l=en",
          linkLabel: "Check AC 1611 status",
        },
        {
          label: "June 12",
          value: "Air Canada AC 5, YUL -> NRT, departure 1:05 PM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=5&t=20260612&o=YUL&c=AC&l=en",
          linkLabel: "Check AC 5 status",
        },
        { label: "Arrival", value: "June 13 arrival in Japan, followed by transfer to Airbnb in Shibuya" },
        { label: "Travel note", value: "Keep transfer details and arrival documents easy to reach." },
      ],
    },
    {
      id: "shibuya",
      type: "lodging",
      title: "Shibuya stay",
      dateLabel: "June 13 - June 19",
      route: "Tokyo base",
      summary: "A Tokyo base in Shibuya for settling in, exploring, and preparing for embarkation.",
      details: [
        { label: "Stay", value: "Airbnb in Shibuya" },
        {
          label: "Address",
          value: "4-chome-48-5 Honmachi, Shibuya City, Prefectura de Tokio 151-0071, Japon",
          link: "https://www.google.com/maps/search/?api=1&query=4-chome-48-5+Honmachi%2C+Shibuya+City%2C+Tokyo+151-0071%2C+Japan",
          linkLabel: "Open in Google Maps",
        },
        { label: "Window", value: "June 13 through June 19, 2026" },
        { label: "Arrival day", value: "June 13 transfer from Narita to Shibuya" },
        { label: "Planning note", value: "Good window for neighborhood dining, shopping, and reservations." },
      ],
    },
    {
      id: "cruise",
      type: "cruise",
      title: "Celebrity Millennium cruise",
      dateLabel: "June 19 - July 1",
      route: "Tokyo -> Japan & Korea -> Tokyo",
      summary: "A 12-night cruise through Japan and Busan, with the final overnight already included.",
      details: [
        { label: "Ship", value: "Celebrity Millennium" },
        { label: "Embarkation", value: "June 19 in Tokyo" },
        { label: "Disembarkation", value: "July 1 with same-day airport transfer planning" },
        { label: "Cruise note", value: "Center timing and packing around the July 1 evening Narita flight." },
      ],
    },
    {
      id: "return",
      type: "flight",
      title: "Return flights",
      dateLabel: "July 1 - July 2",
      route: "NRT -> YUL -> FLL",
      summary: "Disembark in Tokyo, head to Narita, then return home through Montreal.",
      details: [
        {
          label: "July 1",
          value: "Air Canada AC 6, NRT -> YUL, departure 5:35 PM JST",
          link: "https://www.aircanada.com/flifo/flight-details?f=6&t=20260701&o=NRT&c=AC&l=en",
          linkLabel: "Check AC 6 status",
        },
        {
          label: "July 2",
          value: "Air Canada AC 1602, YUL -> FLL, departure 8:10 AM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=1602&t=20260702&o=YUL&c=AC&l=en",
          linkLabel: "Check AC 1602 status",
        },
        { label: "Connection", value: "Montreal transit before the final leg to Fort Lauderdale" },
        { label: "Departure note", value: "Build in comfortable transfer margin from the port to Narita." },
      ],
    },
  ],
  cityTimeline: [
    {
      id: "outbound-flights-city",
      type: "flight",
      title: "Outbound flights to Tokyo",
      dateLabel: "June 11 - June 13",
      route: "FLL -> YUL -> NRT",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Air%20Canada%20A220-300.jpg",
      summary: "Departure from Fort Lauderdale with a Montreal connection before arriving in Japan.",
      details: [
        {
          label: "AC 1611",
          value: "June 11, FLL -> YUL, departure 8:55 PM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=1611&t=20260611&o=FLL&c=AC&l=en",
          linkLabel: "Check AC 1611 status",
        },
        {
          label: "AC 5",
          value: "June 12, YUL -> NRT, departure 1:05 PM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=5&t=20260612&o=YUL&c=AC&l=en",
          linkLabel: "Check AC 5 status",
        },
        { label: "Arrival", value: "June 13 arrival in Japan and transfer to Shibuya." },
      ],
    },
    {
      id: "tokyo-shibuya-stay",
      type: "lodging",
      title: "Tokyo / Shibuya stay",
      dateLabel: "June 13 - June 19",
      route: "Shibuya, Tokyo",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Tokyo_-_Sunset_Skyline.jpg",
      summary: "Settle into the Airbnb in Shibuya and use Tokyo as your first base before cruise embarkation.",
      details: [
        { label: "Stay", value: "Airbnb in Shibuya" },
        {
          label: "Address",
          value: "4-chome-48-5 Honmachi, Shibuya City, Prefectura de Tokio 151-0071, Japon",
          link: "https://www.google.com/maps/search/?api=1&query=4-chome-48-5+Honmachi%2C+Shibuya+City%2C+Tokyo+151-0071%2C+Japan",
          linkLabel: "Open in Google Maps",
        },
        { label: "Focus", value: "Arrival recovery, local exploration, and cruise prep." },
      ],
    },
    {
      id: "tokyo-embarkation",
      type: "cruise",
      title: "Tokyo embarkation",
      dateLabel: "June 19",
      route: "Tokyo cruise terminal",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Tokyo%20Bay%2C%20Japan.jpg",
      summary: "Board Celebrity Millennium and start the 12-night itinerary.",
      details: [
        { label: "Ship", value: "Celebrity Millennium" },
        { label: "Departure", value: "Cruise departs Tokyo on June 19" },
      ],
    },
    {
      id: "kyoto-osaka",
      type: "port",
      title: "Kyoto / Osaka",
      dateLabel: "June 21 - June 22",
      route: "Kansai region",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Skyline_view_of_Osaka.jpg",
      summary: "Two port days in the Kyoto/Osaka area for temples, food, and city exploration.",
      details: [
        { label: "Port days", value: "June 21 and June 22" },
        { label: "Planning note", value: "Great stop for split-day plans between Kyoto and Osaka." },
      ],
    },
    {
      id: "kochi",
      type: "port",
      title: "Kochi",
      dateLabel: "June 23",
      route: "Kochi, Japan",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kochi-City.jpg",
      summary: "Historic and coastal stop on Shikoku.",
      details: [
        { label: "Port", value: "Kochi" },
        { label: "Vibe", value: "Relaxed coastal pace with local history." },
      ],
    },
    {
      id: "busan",
      type: "port",
      title: "Busan",
      dateLabel: "June 25",
      route: "Busan, South Korea",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Busan_%2853854678514%29.jpg",
      summary: "International port day with markets, neighborhoods, and waterfront views.",
      details: [
        { label: "Port", value: "Busan" },
        { label: "Country", value: "South Korea" },
      ],
    },
    {
      id: "nagasaki",
      type: "port",
      title: "Nagasaki",
      dateLabel: "June 26",
      route: "Nagasaki, Japan",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Nagasaki_city_%2849658802002%29.jpg",
      summary: "Historic harbor city with layered cultural sites.",
      details: [
        { label: "Port", value: "Nagasaki" },
        { label: "Focus", value: "Historic districts and harbor viewpoints." },
      ],
    },
    {
      id: "kagoshima",
      type: "port",
      title: "Kagoshima",
      dateLabel: "June 27",
      route: "Kagoshima, Japan",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/20100720_Sakurajima_3846.jpg",
      summary: "Southern Kyushu stop known for volcanic scenery and local culture.",
      details: [
        { label: "Port", value: "Kagoshima" },
        { label: "Focus", value: "Scenic day with Sakurajima views." },
      ],
    },
    {
      id: "shimizu",
      type: "port",
      title: "Shimizu / Mt. Fuji area",
      dateLabel: "June 29",
      route: "Shimizu, Japan",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mount_Fuji_and_Port_of_Shimizu.JPG",
      summary: "Scenic gateway for Fuji views and nearby excursions.",
      details: [
        { label: "Port", value: "Shimizu" },
        { label: "Highlight", value: "Mt. Fuji area viewpoints and shore activities." },
      ],
    },
    {
      id: "tokyo-return",
      type: "flight",
      title: "Return to Tokyo and fly home",
      dateLabel: "July 1 - July 2",
      route: "Tokyo -> Montreal -> Fort Lauderdale",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Tokyo_Night.jpg",
      summary: "Disembark in Tokyo, transfer to Narita, then connect in Montreal for the final leg home.",
      details: [
        {
          label: "AC 6",
          value: "July 1, NRT -> YUL, departure 5:35 PM JST",
          link: "https://www.aircanada.com/flifo/flight-details?f=6&t=20260701&o=NRT&c=AC&l=en",
          linkLabel: "Check AC 6 status",
        },
        {
          label: "AC 1602",
          value: "July 2, YUL -> FLL, departure 8:10 AM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=1602&t=20260702&o=YUL&c=AC&l=en",
          linkLabel: "Check AC 1602 status",
        },
      ],
    },
  ],
  segments: [
    {
      type: "flight",
      title: "Outbound flights",
      kicker: "Transit",
      dateLabel: "June 11 - June 13",
      route: "FLL -> YUL -> NRT",
      description: "A two-leg outbound route with an overnight connection in Montreal before arrival in Japan.",
      meta: ["Air Canada AC 1611", "Air Canada AC 5"],
      details: [
        {
          label: "Leg 1",
          value: "June 11, FLL -> YUL, departure 8:55 PM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=1611&t=20260611&o=FLL&c=AC&l=en",
          linkLabel: "Check AC 1611 status",
        },
        {
          label: "Leg 2",
          value: "June 12, YUL -> NRT, departure 1:05 PM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=5&t=20260612&o=YUL&c=AC&l=en",
          linkLabel: "Check AC 5 status",
        },
        { label: "Arrival", value: "June 13 arrival and transfer to Shibuya" },
      ],
    },
    {
      type: "lodging",
      title: "Shibuya stay",
      kicker: "Lodging",
      dateLabel: "June 13 - June 19",
      route: "Tokyo, Japan",
      description: "A calm Tokyo home base for recovery, city exploration, and pre-cruise planning.",
      meta: ["Airbnb", "6 nights"],
      details: [
        { label: "Property", value: "Airbnb in Shibuya" },
        {
          label: "Address",
          value: "4-chome-48-5 Honmachi, Shibuya City, Prefectura de Tokio 151-0071, Japon",
          link: "https://www.google.com/maps/search/?api=1&query=4-chome-48-5+Honmachi%2C+Shibuya+City%2C+Tokyo+151-0071%2C+Japan",
          linkLabel: "Open in Google Maps",
        },
        { label: "Check-in window", value: "After arriving in Japan on June 13" },
        { label: "Focus", value: "Tokyo exploration, dining plans, and cruise embarkation prep" },
      ],
    },
    {
      type: "cruise",
      title: "Celebrity Millennium cruise",
      kicker: "Cruise",
      dateLabel: "June 19 - July 1",
      route: "Tokyo round trip",
      description: "The centerpiece of the itinerary, mixing city departures, scenic sea days, and port stops.",
      meta: ["12 nights", "Final overnight included"],
      details: [
        { label: "Embarkation", value: "Tokyo on June 19" },
        { label: "Highlights", value: "Kyoto/Osaka, Kochi, Busan, Nagasaki, Kagoshima, and Shimizu" },
        { label: "Disembarkation", value: "July 1 followed by airport transfer day" },
      ],
    },
    {
      type: "flight",
      title: "Return flights",
      kicker: "Transit",
      dateLabel: "July 1 - July 2",
      route: "NRT -> YUL -> FLL",
      description: "Post-cruise departure from Narita followed by the final overnight connection home.",
      meta: ["Air Canada AC 6", "Air Canada AC 1602"],
      details: [
        {
          label: "Leg 1",
          value: "July 1, NRT -> YUL, departure 5:35 PM JST",
          link: "https://www.aircanada.com/flifo/flight-details?f=6&t=20260701&o=NRT&c=AC&l=en",
          linkLabel: "Check AC 6 status",
        },
        {
          label: "Leg 2",
          value: "July 2, YUL -> FLL, departure 8:10 AM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=1602&t=20260702&o=YUL&c=AC&l=en",
          linkLabel: "Check AC 1602 status",
        },
        { label: "Priority", value: "Coordinate disembarkation, luggage, and airport timing smoothly" },
      ],
    },
  ],
  ports: [
    {
      date: "June 19",
      title: "Tokyo departure",
      location: "Tokyo, Japan",
      note: "Embark and settle in before sail-away.",
      coords: [35.6298, 139.77],
    },
    {
      date: "June 20",
      title: "At sea",
      location: "Pacific waters",
      note: "Recovery day and onboard reset.",
      coords: [34.95, 136.95],
    },
    {
      date: "June 21",
      title: "Kyoto/Osaka",
      location: "Kyoto / Osaka region",
      note: "First full Kansai sightseeing day.",
      coords: [34.6577, 135.4297],
    },
    {
      date: "June 22",
      title: "Kyoto/Osaka",
      location: "Kyoto / Osaka region",
      note: "Second port day for a deeper Kyoto or Osaka plan.",
      coords: [34.6577, 135.4297],
    },
    {
      date: "June 23",
      title: "Kochi",
      location: "Kochi, Japan",
      note: "Historic and coastal stop on Shikoku.",
      coords: [33.4938, 133.5321],
    },
    {
      date: "June 24",
      title: "At sea",
      location: "Cruising day",
      note: "Slower day for ship time, dining, and rest.",
      coords: [34.2, 130.95],
    },
    {
      date: "June 25",
      title: "Busan",
      location: "Busan, South Korea",
      note: "International port day with markets and waterfront energy.",
      coords: [35.1028, 129.0403],
    },
    {
      date: "June 26",
      title: "Nagasaki",
      location: "Nagasaki, Japan",
      note: "Historic harbor city with layered cultural sites.",
      coords: [32.7448, 129.8737],
    },
    {
      date: "June 27",
      title: "Kagoshima",
      location: "Kagoshima, Japan",
      note: "Southern Kyushu stop with volcanic scenery nearby.",
      coords: [31.5966, 130.5571],
    },
    {
      date: "June 28",
      title: "At sea",
      location: "Cruising day",
      note: "Onboard day before the Mt. Fuji area approach.",
      coords: [33.2, 135.4],
    },
    {
      date: "June 29",
      title: "Shimizu / Mt. Fuji area",
      location: "Shimizu, Japan",
      note: "Scenic gateway for Fuji views and excursions.",
      coords: [35.0158, 138.4898],
    },
    {
      date: "June 30",
      title: "Return toward Tokyo",
      location: "Approach to Tokyo",
      note: "Final full sailing day heading back to the capital.",
      coords: [35.33, 139.25],
    },
    {
      date: "July 1",
      title: "Disembark / airport transfer day",
      location: "Tokyo, Japan",
      note: "Disembark in Tokyo and transfer for the evening Narita flight.",
      coords: [35.6298, 139.77],
    },
  ],
  notes: [
    {
      title: "Packing notes",
      items: [
        "Keep passports, cruise documents, and both Air Canada confirmations together.",
        "Pack one compact arrival-day bag for the transfer to Shibuya and the first Tokyo evening.",
        "Bring lightweight layers for city walking, sea days, and cool indoor spaces.",
      ],
    },
    {
      title: "Booking reminders",
      items: [
        "Confirm Airbnb check-in instructions and backup contact timing before departure.",
        "Review cruise boarding requirements, luggage tags, and any specialty reservations.",
        "Double-check the July 1 Narita transfer plan so the 5:35 PM JST departure stays comfortable.",
      ],
    },
    {
      title: "Reservation ideas",
      items: [
        "Shortlist a few Shibuya and central Tokyo dinner spots for the pre-cruise stay.",
        "Consider advance booking for high-demand Tokyo attractions in mid-June.",
        "Sketch optional port priorities for Kyoto/Osaka, Busan, and Shimizu.",
      ],
    },
    {
      title: "Airport transfer notes",
      items: [
        "Timezone key for this plan: ET = Eastern Time, JST = Japan Standard Time.",
        "Save airport, Airbnb, and terminal addresses offline before departure.",
        "Compare Narita Express, airport bus, and private transfer comfort for the return day.",
        "Keep luggage handling simple on July 1 so port exit to airport feels smooth.",
      ],
    },
  ],
};
