// Itinerary configuration data.
// Edit this file when trip details change.
window.ITINERARY_DATA = {
  trip: {
    title: "Japan 2026",
    subtitle: "June 11 - July 2, 2026",
    summary:
      "Fort Lauderdale -> Montreal -> Tokyo -> Shibuya stay -> Celebrity Millennium cruise -> Tokyo -> Montreal -> Fort Lauderdale",
    startDate: "2026-06-11",
    endDate: "2026-07-02",
    returnDate: "2026-07-02",
  },
  stats: [
    {
      label: "Tokyo stay",
      value: "June 13 - June 19",
      detail: "Airbnb in Shibuya before embarking on the cruise.",
    },
    {
      label: "Cruise dates",
      value: "June 19 - July 1",
      detail: "Celebrity Millennium, 12-night sailing with final overnight included.",
      link: "https://www.celebritycruises.com/myaccount/",
      linkLabel: "Open Celebrity account",
    },
    {
      label: "Return date",
      value: "July 2, 2026",
      detail: "Montreal connection completes the route back to Fort Lauderdale.",
    },
  ],
  timeline: [
    {
      id: "outbound",
      type: "flight",
      title: "Outbound flights",
      dateLabel: "June 11 - June 13",
      route: "FLL -> YUL -> NRT",
      summary: "Evening departure from Fort Lauderdale, overnight connection, then nonstop to Tokyo.",
      details: [
        {
          label: "June 11",
          value: "Air Canada AC 1611, FLL -> YUL, departure 8:55 PM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=1611&t=20260611&o=FLL&c=AC&l=en",
          linkLabel: "Check AC 1611 status",
        },
        {
          label: "June 12",
          value: "Air Canada AC 5, YUL -> NRT, departure 1:05 PM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=5&t=20260612&o=YUL&c=AC&l=en",
          linkLabel: "Check AC 5 status",
        },
        { label: "Arrival", value: "June 13 arrival in Japan, followed by transfer to Airbnb in Shibuya" },
        { label: "Travel note", value: "Keep transfer details and arrival documents easy to reach." },
      ],
    },
    {
      id: "shibuya",
      type: "lodging",
      title: "Shibuya stay",
      dateLabel: "June 13 - June 19",
      route: "Tokyo base",
      summary: "A Tokyo base in Shibuya for settling in, exploring, and preparing for embarkation.",
      details: [
        { label: "Stay", value: "Airbnb in Shibuya" },
        {
          label: "Address",
          value: "4-chome-48-5 Honmachi, Shibuya City, Prefectura de Tokio 151-0071, Japon",
          link: "https://www.google.com/maps/search/?api=1&query=4-chome-48-5+Honmachi%2C+Shibuya+City%2C+Tokyo+151-0071%2C+Japan",
          linkLabel: "Open in Google Maps",
        },
        { label: "Window", value: "June 13 through June 19, 2026" },
        { label: "Arrival day", value: "June 13 transfer from Narita to Shibuya" },
        { label: "Planning note", value: "Good window for neighborhood dining, shopping, and reservations." },
      ],
    },
    {
      id: "cruise",
      type: "cruise",
      title: "Celebrity Millennium cruise",
      dateLabel: "June 19 - July 1",
      route: "Tokyo -> Japan & Korea -> Tokyo",
      summary: "A 12-night cruise through Japan and Busan, with the final overnight already included.",
      details: [
        { label: "Ship", value: "Celebrity Millennium" },
        { label: "Embarkation", value: "June 19 in Tokyo" },
        { label: "Disembarkation", value: "July 1 with same-day airport transfer planning" },
        { label: "Cruise note", value: "Center timing and packing around the July 1 evening Narita flight." },
      ],
    },
    {
      id: "return",
      type: "flight",
      title: "Return flights",
      dateLabel: "July 1 - July 2",
      route: "NRT -> YUL -> FLL",
      summary: "Disembark in Tokyo, head to Narita, then return home through Montreal.",
      details: [
        {
          label: "July 1",
          value: "Air Canada AC 6, NRT -> YUL, departure 5:35 PM JST",
          link: "https://www.aircanada.com/flifo/flight-details?f=6&t=20260701&o=NRT&c=AC&l=en",
          linkLabel: "Check AC 6 status",
        },
        {
          label: "July 2",
          value: "Air Canada AC 1602, YUL -> FLL, departure 8:10 AM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=1602&t=20260702&o=YUL&c=AC&l=en",
          linkLabel: "Check AC 1602 status",
        },
        { label: "Connection", value: "Montreal transit before the final leg to Fort Lauderdale" },
        { label: "Departure note", value: "Build in comfortable transfer margin from the port to Narita." },
      ],
    },
  ],
  cityTimeline: [
    {
      id: "cruise-day-1",
      type: "cruise",
      title: "Day 1 - Tokyo, Japan",
      dateLabel: "Fri, Jun 19",
      route: "Tokyo departure",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Tokyo%20Bay%2C%20Japan.jpg",
      summary: "Embark on Celebrity Millennium in Tokyo and begin the cruise.",
      details: [
        { label: "Ship", value: "Celebrity Millennium" },
        { label: "Departure", value: "Departs at 4:30 PM JST" },
      ],
    },
    {
      id: "cruise-day-2",
      type: "cruise",
      title: "Day 2 - Day at Sea",
      dateLabel: "Sat, Jun 20",
      route: "Celebrity Millennium",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Tokyo%20Bay%2C%20Japan.jpg",
      summary: "Full day at sea aboard Celebrity Millennium.",
      details: [
        { label: "Ship", value: "Celebrity Millennium" },
        { label: "Status", value: "At sea" },
      ],
    },
    {
      id: "cruise-day-3",
      type: "port",
      title: "Day 3 - Kyoto (Osaka), Japan",
      dateLabel: "Sun, Jun 21",
      route: "Kyoto (Osaka)",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Skyline_view_of_Osaka.jpg",
      summary: "First day docked in Kyoto (Osaka).",
      details: [
        { label: "Docked", value: "From 8:00 AM JST" },
        { label: "Window", value: "Overnight port call continues into Day 4" },
      ],
    },
    {
      id: "cruise-day-4",
      type: "port",
      title: "Day 4 - Kyoto (Osaka), Japan",
      dateLabel: "Mon, Jun 22",
      route: "Kyoto (Osaka)",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Skyline_view_of_Osaka.jpg",
      summary: "Second day in Kyoto (Osaka) before evening departure.",
      details: [
        { label: "Docked", value: "Until 6:00 PM JST" },
        { label: "Window", value: "Continuation of the Day 3 overnight stop" },
      ],
    },
    {
      id: "cruise-day-5",
      type: "port",
      title: "Day 5 - Kochi, Japan",
      dateLabel: "Tue, Jun 23",
      route: "Kochi, Japan",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kochi-City.jpg",
      summary: "Port day in Kochi.",
      details: [
        { label: "Docked", value: "8:00 AM - 5:00 PM JST" },
      ],
    },
    {
      id: "cruise-day-6",
      type: "cruise",
      title: "Day 6 - Day at Sea",
      dateLabel: "Wed, Jun 24",
      route: "Celebrity Millennium",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Tokyo%20Bay%2C%20Japan.jpg",
      summary: "Full day at sea aboard Celebrity Millennium.",
      details: [
        { label: "Ship", value: "Celebrity Millennium" },
        { label: "Status", value: "At sea" },
      ],
    },
    {
      id: "cruise-day-7",
      type: "port",
      title: "Day 7 - Busan, South Korea",
      dateLabel: "Thu, Jun 25",
      route: "Busan, South Korea",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Busan_%2853854678514%29.jpg",
      summary: "International port day in Busan.",
      details: [
        { label: "Docked", value: "7:00 AM - 5:00 PM JST" },
      ],
    },
    {
      id: "cruise-day-8",
      type: "port",
      title: "Day 8 - Nagasaki, Japan",
      dateLabel: "Fri, Jun 26",
      route: "Nagasaki, Japan",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Nagasaki_city_%2849658802002%29.jpg",
      summary: "Port day in Nagasaki.",
      details: [
        { label: "Docked", value: "8:00 AM - 7:00 PM JST" },
      ],
    },
    {
      id: "cruise-day-9",
      type: "port",
      title: "Day 9 - Kagoshima, Japan",
      dateLabel: "Sat, Jun 27",
      route: "Kagoshima, Japan",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/20100720_Sakurajima_3846.jpg",
      summary: "Port day in Kagoshima.",
      details: [
        { label: "Docked", value: "7:00 AM - 5:00 PM JST" },
      ],
    },
    {
      id: "cruise-day-10",
      type: "cruise",
      title: "Day 10 - Day at Sea",
      dateLabel: "Sun, Jun 28",
      route: "Celebrity Millennium",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Tokyo%20Bay%2C%20Japan.jpg",
      summary: "Full day at sea aboard Celebrity Millennium.",
      details: [
        { label: "Ship", value: "Celebrity Millennium" },
        { label: "Status", value: "At sea" },
      ],
    },
    {
      id: "cruise-day-11",
      type: "port",
      title: "Day 11 - Mt Fuji (Shimizu), Japan",
      dateLabel: "Mon, Jun 29",
      route: "Mt Fuji (Shimizu), Japan",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mount_Fuji_and_Port_of_Shimizu.JPG",
      summary: "Port day in Mt Fuji (Shimizu).",
      details: [
        { label: "Docked", value: "7:00 AM - 6:00 PM JST" },
      ],
    },
    {
      id: "cruise-day-12",
      type: "port",
      title: "Day 12 - Tokyo, Japan",
      dateLabel: "Tue, Jun 30",
      route: "Tokyo, Japan",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Tokyo_Night.jpg",
      summary: "Tokyo port call begins.",
      details: [
        { label: "Docked", value: "From 8:00 AM JST" },
      ],
    },
    {
      id: "cruise-day-13",
      type: "port",
      title: "Day 13 - Tokyo, Japan",
      dateLabel: "Wed, Jul 1",
      route: "Tokyo, Japan",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Tokyo_Night.jpg",
      summary: "Final Tokyo day / disembarkation day.",
      details: [
        { label: "Status", value: "In Tokyo (port day/disembarkation day)" },
      ],
    },
  ],
  segments: [
    {
      type: "flight",
      title: "Outbound flights",
      kicker: "Transit",
      dateLabel: "June 11 - June 13",
      route: "FLL -> YUL -> NRT",
      description: "A two-leg outbound route with an overnight connection in Montreal before arrival in Japan.",
      meta: ["Air Canada AC 1611", "Air Canada AC 5"],
      details: [
        {
          label: "Leg 1",
          value: "June 11, FLL -> YUL, departure 8:55 PM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=1611&t=20260611&o=FLL&c=AC&l=en",
          linkLabel: "Check AC 1611 status",
        },
        {
          label: "Leg 2",
          value: "June 12, YUL -> NRT, departure 1:05 PM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=5&t=20260612&o=YUL&c=AC&l=en",
          linkLabel: "Check AC 5 status",
        },
        { label: "Arrival", value: "June 13 arrival and transfer to Shibuya" },
      ],
    },
    {
      type: "lodging",
      title: "Shibuya stay",
      kicker: "Lodging",
      dateLabel: "June 13 - June 19",
      route: "Tokyo, Japan",
      description: "A calm Tokyo home base for recovery, city exploration, and pre-cruise planning.",
      meta: ["Airbnb", "6 nights"],
      details: [
        { label: "Property", value: "Airbnb in Shibuya" },
        {
          label: "Address",
          value: "4-chome-48-5 Honmachi, Shibuya City, Prefectura de Tokio 151-0071, Japon",
          link: "https://www.google.com/maps/search/?api=1&query=4-chome-48-5+Honmachi%2C+Shibuya+City%2C+Tokyo+151-0071%2C+Japan",
          linkLabel: "Open in Google Maps",
        },
        { label: "Check-in window", value: "After arriving in Japan on June 13" },
        { label: "Focus", value: "Tokyo exploration, dining plans, and cruise embarkation prep" },
      ],
    },
    {
      type: "cruise",
      title: "Celebrity Millennium cruise",
      kicker: "Cruise",
      dateLabel: "June 19 - July 1",
      route: "Tokyo round trip",
      description: "The centerpiece of the itinerary, mixing city departures, scenic sea days, and port stops.",
      meta: ["12 nights", "Final overnight included"],
      details: [
        { label: "Embarkation", value: "Tokyo on June 19" },
        { label: "Highlights", value: "Kyoto/Osaka, Kochi, Busan, Nagasaki, Kagoshima, and Shimizu" },
        { label: "Disembarkation", value: "July 1 followed by airport transfer day" },
      ],
    },
    {
      type: "flight",
      title: "Return flights",
      kicker: "Transit",
      dateLabel: "July 1 - July 2",
      route: "NRT -> YUL -> FLL",
      description: "Post-cruise departure from Narita followed by the final overnight connection home.",
      meta: ["Air Canada AC 6", "Air Canada AC 1602"],
      details: [
        {
          label: "Leg 1",
          value: "July 1, NRT -> YUL, departure 5:35 PM JST",
          link: "https://www.aircanada.com/flifo/flight-details?f=6&t=20260701&o=NRT&c=AC&l=en",
          linkLabel: "Check AC 6 status",
        },
        {
          label: "Leg 2",
          value: "July 2, YUL -> FLL, departure 8:10 AM ET",
          link: "https://www.aircanada.com/flifo/flight-details?f=1602&t=20260702&o=YUL&c=AC&l=en",
          linkLabel: "Check AC 1602 status",
        },
        { label: "Priority", value: "Coordinate disembarkation, luggage, and airport timing smoothly" },
      ],
    },
  ],
  ports: [
    {
      date: "Fri, Jun 19",
      title: "Tokyo departure",
      location: "Tokyo, Japan",
      note: "Departs at 4:30 PM JST.",
      coords: [35.6298, 139.77],
    },
    {
      date: "Sat, Jun 20",
      title: "Day at Sea",
      location: "Celebrity Millennium",
      note: "Day at sea.",
      coords: [34.95, 136.95],
    },
    {
      date: "Sun, Jun 21",
      title: "Kyoto (Osaka)",
      location: "Kyoto (Osaka), Japan",
      note: "Docked from 8:00 AM JST.",
      coords: [34.6577, 135.4297],
    },
    {
      date: "Mon, Jun 22",
      title: "Kyoto (Osaka)",
      location: "Kyoto (Osaka), Japan",
      note: "Docked until 6:00 PM JST.",
      coords: [34.6577, 135.4297],
    },
    {
      date: "Tue, Jun 23",
      title: "Kochi",
      location: "Kochi, Japan",
      note: "Docked from 8:00 AM - 5:00 PM JST.",
      coords: [33.4938, 133.5321],
    },
    {
      date: "Wed, Jun 24",
      title: "Day at Sea",
      location: "Celebrity Millennium",
      note: "Day at sea.",
      coords: [34.2, 130.95],
    },
    {
      date: "Thu, Jun 25",
      title: "Busan",
      location: "Busan, South Korea",
      note: "Docked from 7:00 AM - 5:00 PM JST.",
      coords: [35.1028, 129.0403],
    },
    {
      date: "Fri, Jun 26",
      title: "Nagasaki",
      location: "Nagasaki, Japan",
      note: "Docked from 8:00 AM - 7:00 PM JST.",
      coords: [32.7448, 129.8737],
    },
    {
      date: "Sat, Jun 27",
      title: "Kagoshima",
      location: "Kagoshima, Japan",
      note: "Docked from 7:00 AM - 5:00 PM JST.",
      coords: [31.5966, 130.5571],
    },
    {
      date: "Sun, Jun 28",
      title: "Day at Sea",
      location: "Celebrity Millennium",
      note: "Day at sea.",
      coords: [33.2, 135.4],
    },
    {
      date: "Mon, Jun 29",
      title: "Mt Fuji (Shimizu)",
      location: "Mt Fuji (Shimizu), Japan",
      note: "Docked from 7:00 AM - 6:00 PM JST.",
      coords: [35.0158, 138.4898],
    },
    {
      date: "Tue, Jun 30",
      title: "Tokyo",
      location: "Tokyo, Japan",
      note: "Docked from 8:00 AM JST.",
      coords: [35.6298, 139.77],
    },
    {
      date: "Wed, Jul 1",
      title: "Tokyo",
      location: "Tokyo, Japan",
      note: "In Tokyo (port day/disembarkation day).",
      coords: [35.6298, 139.77],
    },
  ],
  notes: [
    {
      title: "Packing notes",
      items: [
        "Keep passports, cruise documents, and both Air Canada confirmations together.",
        "Pack one compact arrival-day bag for the transfer to Shibuya and the first Tokyo evening.",
        "Bring lightweight layers for city walking, sea days, and cool indoor spaces.",
      ],
    },
    {
      title: "Booking reminders",
      items: [
        "Confirm Airbnb check-in instructions and backup contact timing before departure.",
        "Review cruise boarding requirements, luggage tags, and any specialty reservations.",
        "Double-check the July 1 Narita transfer plan so the 5:35 PM JST departure stays comfortable.",
      ],
    },
    {
      title: "Reservation ideas",
      items: [
        "Shortlist a few Shibuya and central Tokyo dinner spots for the pre-cruise stay.",
        "Consider advance booking for high-demand Tokyo attractions in mid-June.",
        "Sketch optional port priorities for Kyoto/Osaka, Busan, and Shimizu.",
      ],
    },
    {
      title: "Airport transfer notes",
      items: [
        "Timezone key for this plan: ET = Eastern Time, JST = Japan Standard Time.",
        "Save airport, Airbnb, and terminal addresses offline before departure.",
        "Compare Narita Express, airport bus, and private transfer comfort for the return day.",
        "Keep luggage handling simple on July 1 so port exit to airport feels smooth.",
      ],
    },
  ],
};
